---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-helloworld
  namespace: test
  labels:
    app: spring-boot-helloworld
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30666
  selector:
    app: spring-boot-helloworld
