apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  pvc-sfs-maven-cache
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: "gitops-data"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  #storageClassName: csi-nas
