global:
  resolve_timeout: 5m
route: 
  group_by: ['job']
  group_wait: 30s
  group_interval: 12h
  repeat_interval: 12h
  receiver: webhook
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://webhook-dingtalk.monitoring.svc.cluster.local:8060/dingtalk/webhook1/send'
    send_resolved: true

